// T021 [US1]: preview cards are generated by the shared terrain/material/sky pipeline at
// the fixed seed, all three decode, rows are upright, and failures surface as retryable
// card errors rather than silent blanks. Runs inside the verification build only.
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Browser, Page } from "playwright";
import { launchChromium } from "../../scripts/browser-harness";
import { BASE, collectPageErrors, gotoAndWaitChooser } from "./browser-helpers";

let browser: Browser;

beforeAll(async () => {
  browser = await launchChromium();
});

afterAll(async () => {
  await browser?.close();
});

async function cardInfo(page: Page) {
  return page.evaluate(() => {
    const out: Record<string, { src: string; state: string; w: number; h: number }> = {};
    for (const id of ["nature", "alien", "arctic"]) {
      const img = document.querySelector(
        `img[data-theme-img="${id}"]`,
      ) as HTMLImageElement | null;
      const fb = document.querySelector(
        `[data-theme-fallback="${id}"]`,
      ) as HTMLElement | null;
      if (img && fb) {
        out[id] = {
          src: img.currentSrc || img.src,
          state: img.dataset.state ?? "pending",
          w: img.naturalWidth,
          h: img.naturalHeight,
        };
      }
    }
    return out;
  });
}

describe("theme previews", () => {
  it("all three cards decode real shared-generator images", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    const errs = collectPageErrors(page);
    try {
      await gotoAndWaitChooser(page, "?seed=42&renderTest");
      // wait for every card to reach a terminal state
      await page.waitForFunction(
        () =>
          ["nature", "alien", "arctic"].every((id) => {
            const img = document.querySelector(
              `img[data-theme-img="${id}"]`,
            ) as HTMLImageElement | null;
            return img && (img.dataset.state === "ready" || img.dataset.state === "failed");
          }),
        { timeout: 120_000 },
      );
      const cards = await cardInfo(page);
      for (const id of ["nature", "alien", "arctic"]) {
        expect(cards[id]?.state, `${id} state`).toBe("ready");
        expect(cards[id]?.src, `${id} src`).toMatch(/^blob:/);
        expect(cards[id]?.w).toBe(256);
        expect(cards[id]?.h).toBe(144);
      }
      expect(errs.pageErrors).toEqual([]);
    } finally {
      await page.close();
    }
  });

  it("cards are non-blank and differ between themes (real terrain, not placeholders)", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    try {
      await gotoAndWaitChooser(page, "?seed=42&renderTest");
      await page.waitForFunction(
        () =>
          ["nature", "alien", "arctic"].every((id) => {
            const img = document.querySelector(
              `img[data-theme-img="${id}"]`,
            ) as HTMLImageElement | null;
            return img?.dataset.state === "ready";
          }),
        { timeout: 120_000 },
      );
      const sigs = await page.evaluate(() => {
        const out: Record<string, number> = {};
        for (const id of ["nature", "alien", "arctic"]) {
          const img = document.querySelector(
            `img[data-theme-img="${id}"]`,
          ) as HTMLImageElement;
          const c = document.createElement("canvas");
          c.width = img.naturalWidth;
          c.height = img.naturalHeight;
          const ctx = c.getContext("2d")!;
          ctx.drawImage(img, 0, 0);
          const d = ctx.getImageData(0, 0, c.width, c.height).data;
          // cheap signature: count of unique colours + mean hue bucket
          const seen = new Set<number>();
          let sum = 0;
          for (let i = 0; i < d.length; i += 64) {
            seen.add((d[i] << 16) | (d[i + 1] << 8) | d[i + 2]);
            sum += d[i] + d[i + 1] + d[i + 2];
          }
          out[id] = seen.size * 1e6 + Math.round(sum / (d.length / 64));
        }
        return out;
      });
      for (const id of ["nature", "alien", "arctic"]) {
        expect(Math.floor(sigs[id] / 1e6), `${id} unique colours`).toBeGreaterThan(16);
      }
      // each pair differs in its signature — three visibly different worlds
      expect(sigs.nature).not.toBe(sigs.alien);
      expect(sigs.nature).not.toBe(sigs.arctic);
      expect(sigs.alien).not.toBe(sigs.arctic);
    } finally {
      await page.close();
    }
  });

  it("card images stay cached when the chooser reopens", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    try {
      await gotoAndWaitChooser(page, "?seed=42&renderTest");
      await page.waitForFunction(
        () =>
          (document.querySelector('img[data-theme-img="alien"]') as HTMLImageElement)
            ?.dataset.state === "ready",
        { timeout: 120_000 },
      );
      const before = (await cardInfo(page)).alien.src;
      // fly alien, reopen via Change theme — the same URL must still be attached
      await page.click('#chooser input[value="alien"]');
      await page.click("#fly");
      await page.waitForFunction(() => document.body.dataset.phase === "flying", {
        timeout: 120_000,
      });
      await page.click("#change-theme");
      const after = (await cardInfo(page)).alien.src;
      expect(after).toBe(before);
    } finally {
      await page.close();
    }
  });

  it("injected preview failure shows the fallback and keeps the card retryable", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    try {
      // fail only the arctic card via the T029 verification adapter
      await page.addInitScript(() => {
        (window as unknown as { __verifyPreview?: (id: string) => unknown }).__verifyPreview =
          (id: string) => (id === "arctic" ? { kind: "fail" } : undefined);
      });
      await page.goto(`${BASE}/?seed=42&renderTest`, { waitUntil: "load" });
      await page.waitForFunction(() => document.body.dataset.phase === "choosing", {
        timeout: 120_000,
      });
      await page.waitForFunction(
        () =>
          (document.querySelector('img[data-theme-img="arctic"]') as HTMLImageElement)
            ?.dataset.state === "failed",
        { timeout: 60_000 },
      );
      const cards = await cardInfo(page);
      expect(cards.arctic.state).toBe("failed");
      expect(cards.nature.state).toBe("ready");
      // a startup error is announced (not silent)
      const error = await page.evaluate(
        () => document.getElementById("chooser-error")?.textContent ?? "",
      );
      expect(error.length).toBeGreaterThan(0);
    } finally {
      await page.close();
    }
  });
});
