// T021 [US1]: preview cards are generated by the shared terrain/material/sky pipeline at
// the fixed seed, all three decode, rows are upright, and failures surface as retryable
// card errors rather than silent blanks. Runs inside the verification build only.
// T011 [US2]: the set grows to nine cards — six aircraft images rendered from the real
// boot-built geometry at the same 256x144 size, bootReady waits on all nine, and an
// injected aircraft-card failure leaves name and radio usable without ever showing
// another card's image until Retry completes it.
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Browser, Page } from "playwright";
import { launchChromium } from "../../scripts/browser-harness";
import { BASE, collectPageErrors, gotoAndWaitChooser } from "./browser-helpers";

let browser: Browser;

beforeAll(async () => {
  browser = await launchChromium();
});

afterAll(async () => {
  await browser?.close();
});

async function cardInfo(page: Page, kind: "theme" | "aircraft" = "theme") {
  return page.evaluate((k) => {
    const imgAttr = k === "theme" ? "data-theme-img" : "data-aircraft-img";
    const fbAttr = k === "theme" ? "data-theme-fallback" : "data-aircraft-fallback";
    const out: Record<string, { src: string; state: string; w: number; h: number }> = {};
    for (const img of document.querySelectorAll(`img[${imgAttr}]`)) {
      const el = img as HTMLImageElement;
      const id = el.getAttribute(imgAttr);
      if (!id || !document.querySelector(`[${fbAttr}="${id}"]`)) continue;
      out[id] = {
        src: el.currentSrc || el.src,
        state: el.dataset.state ?? "pending",
        w: el.naturalWidth,
        h: el.naturalHeight,
      };
    }
    return out;
  }, kind);
}

describe("theme previews", () => {
  it("all three cards decode real shared-generator images", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    const errs = collectPageErrors(page);
    try {
      await gotoAndWaitChooser(page, "?seed=42&renderTest");
      // wait for every card to reach a terminal state
      await page.waitForFunction(
        () =>
          ["nature", "alien", "arctic"].every((id) => {
            const img = document.querySelector(
              `img[data-theme-img="${id}"]`,
            ) as HTMLImageElement | null;
            return img && (img.dataset.state === "ready" || img.dataset.state === "failed");
          }),
        undefined,
    { timeout: 120_000 },
    );
      const cards = await cardInfo(page);
      for (const id of ["nature", "alien", "arctic"]) {
        expect(cards[id]?.state, `${id} state`).toBe("ready");
        expect(cards[id]?.src, `${id} src`).toMatch(/^blob:/);
        expect(cards[id]?.w).toBe(256);
        expect(cards[id]?.h).toBe(144);
      }
      expect(errs.pageErrors).toEqual([]);
    } finally {
      await page.close();
    }
  });

  it("cards are non-blank and differ between themes (real terrain, not placeholders)", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    try {
      await gotoAndWaitChooser(page, "?seed=42&renderTest");
      await page.waitForFunction(
        () =>
          ["nature", "alien", "arctic"].every((id) => {
            const img = document.querySelector(
              `img[data-theme-img="${id}"]`,
            ) as HTMLImageElement | null;
            return img?.dataset.state === "ready";
          }),
        undefined,
    { timeout: 120_000 },
    );
      const sigs = await page.evaluate(() => {
        const out: Record<string, number> = {};
        for (const id of ["nature", "alien", "arctic"]) {
          const img = document.querySelector(
            `img[data-theme-img="${id}"]`,
          ) as HTMLImageElement;
          const c = document.createElement("canvas");
          c.width = img.naturalWidth;
          c.height = img.naturalHeight;
          const ctx = c.getContext("2d")!;
          ctx.drawImage(img, 0, 0);
          const d = ctx.getImageData(0, 0, c.width, c.height).data;
          // cheap signature: count of unique colours + mean hue bucket
          const seen = new Set<number>();
          let sum = 0;
          for (let i = 0; i < d.length; i += 64) {
            seen.add((d[i] << 16) | (d[i + 1] << 8) | d[i + 2]);
            sum += d[i] + d[i + 1] + d[i + 2];
          }
          out[id] = seen.size * 1e6 + Math.round(sum / (d.length / 64));
        }
        return out;
      });
      for (const id of ["nature", "alien", "arctic"]) {
        expect(Math.floor(sigs[id] / 1e6), `${id} unique colours`).toBeGreaterThan(16);
      }
      // each pair differs in its signature — three visibly different worlds
      expect(sigs.nature).not.toBe(sigs.alien);
      expect(sigs.nature).not.toBe(sigs.arctic);
      expect(sigs.alien).not.toBe(sigs.arctic);
    } finally {
      await page.close();
    }
  });

  it("card images stay cached when the chooser reopens", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    try {
      await gotoAndWaitChooser(page, "?seed=42&renderTest");
      await page.waitForFunction(
        () =>
          (document.querySelector('img[data-theme-img="alien"]') as HTMLImageElement)
            ?.dataset.state === "ready",
        undefined,
    { timeout: 120_000 },
    );
      const before = (await cardInfo(page)).alien.src;
      // fly alien, reopen via Change theme — the same URL must still be attached
      await page.click('#chooser input[value="alien"]');
      await page.click("#fly");
      await page.waitForFunction(() => document.body.dataset.phase === "flying", undefined, {
        timeout: 120_000,
      });
      await page.click("#change-theme");
      const after = (await cardInfo(page)).alien.src;
      expect(after).toBe(before);
    } finally {
      await page.close();
    }
  });

  it("injected preview failure shows the fallback and keeps the card retryable", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    try {
      // fail only the arctic card via the T029 verification adapter
      await page.addInitScript(() => {
        (window as unknown as { __verifyPreview?: (id: string) => unknown }).__verifyPreview =
          (id: string) => (id === "arctic" ? { kind: "fail" } : undefined);
      });
      await page.goto(`${BASE}/?seed=42&renderTest`, { waitUntil: "load" });
      await page.waitForFunction(() => document.body.dataset.phase === "choosing", undefined, {
        timeout: 120_000,
      });
      await page.waitForFunction(
        () =>
          (document.querySelector('img[data-theme-img="arctic"]') as HTMLImageElement)
            ?.dataset.state === "failed",
        undefined,
    { timeout: 60_000 },
    );
      const cards = await cardInfo(page);
      expect(cards.arctic.state).toBe("failed");
      expect(cards.nature.state).toBe("ready");
      // a startup error is announced (not silent)
      const error = await page.evaluate(
        () => document.getElementById("chooser-error")?.textContent ?? "",
      );
      expect(error.length).toBeGreaterThan(0);
    } finally {
      await page.close();
    }
  });
});

const AIRCRAFT_IDS = ["helicopter", "light", "fighter", "airliner", "biplane", "glider"];
describe("aircraft previews", () => {
  it("nine cards: all six aircraft images decode at 256x144", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    const errs = collectPageErrors(page);
    try {
      await gotoAndWaitChooser(page, "?seed=42&renderTest");
      const counts = await page.evaluate(() => ({
        cards: document.querySelectorAll("#chooser label.card").length,
        aircraft: document.querySelectorAll("img[data-aircraft-img]").length,
      }));
      expect(counts).toEqual({ cards: 9, aircraft: 6 });
      await page.waitForFunction(
        () =>
          [...document.querySelectorAll("img[data-theme-img], img[data-aircraft-img]")].every((img) => {
            const s = (img as HTMLImageElement).dataset.state;
            return s === "ready" || s === "failed";
          }),
        undefined,
    { timeout: 120_000 },
    );
      const cards = await cardInfo(page, "aircraft");
      expect(Object.keys(cards)).toEqual(AIRCRAFT_IDS);
      for (const id of AIRCRAFT_IDS) {
        expect(cards[id]?.state, `${id} state`).toBe("ready");
        expect(cards[id]?.src, `${id} src`).toMatch(/^blob:/);
        expect(cards[id]?.w).toBe(256);
        expect(cards[id]?.h).toBe(144);
      }
      expect(errs.pageErrors).toEqual([]);
    } finally {
      await page.close();
    }
  });

  it("the chooser stays non-interactive until all nine cards resolve", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    const errs = collectPageErrors(page);
    try {
      // hold the last card back: glider's readback sits behind the verify delay
      await page.addInitScript(() => {
        (window as unknown as { __verifyPreview?: (id: string) => unknown }).__verifyPreview =
          (id: string) => (id === "glider" ? { kind: "delay", ms: 10_000 } : undefined);
      });
      await page.goto(`${BASE}/?seed=42&renderTest`, { waitUntil: "load" });
      const counts = await page.evaluate(() => ({
        cards: document.querySelectorAll("#chooser label.card").length,
        aircraft: document.querySelectorAll("img[data-aircraft-img]").length,
      }));
      expect(counts).toEqual({ cards: 9, aircraft: 6 });
      // eight cards settle while glider is still held: bootReady must not fire early
      await page.waitForFunction(
        () =>
          document.body.dataset.phase === "booting" &&
          [...document.querySelectorAll("img[data-theme-img], img[data-aircraft-img]")].filter((img) => {
            const s = (img as HTMLImageElement).dataset.state;
            return s === "ready" || s === "failed";
          }).length === 8,
        undefined,
    { timeout: 120_000 },
    );
      const held = await page.evaluate(() => ({
        phase: document.body.dataset.phase,
        readyChooser: document.body.dataset.readyChooser,
        flyDisabled: (document.getElementById("fly") as HTMLButtonElement).disabled,
      }));
      expect(held.phase).toBe("booting");
      expect(held.readyChooser).not.toBe("true");
      expect(held.flyDisabled).toBe(true);
      // once the ninth lands the chooser turns interactive
      await page.waitForFunction(() => document.body.dataset.readyChooser === "true", undefined, {
        timeout: 120_000,
      });
      const settled = await page.evaluate(() => ({
        phase: document.body.dataset.phase,
        flyDisabled: (document.getElementById("fly") as HTMLButtonElement).disabled,
      }));
      expect(settled.phase).toBe("choosing");
      expect(settled.flyDisabled).toBe(false);
      expect(errs.pageErrors).toEqual([]);
    } finally {
      await page.close();
    }
  });

  it("an injected aircraft-card failure keeps name and radio usable, never shows another card's image, and Retry completes it", async () => {
    const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
    const errs = collectPageErrors(page);
    try {
      // fail only the Passenger Jet card via the verification adapter
      await page.addInitScript(() => {
        (window as unknown as { __verifyPreview?: (id: string) => unknown }).__verifyPreview =
          (id: string) => (id === "airliner" ? { kind: "fail" } : undefined);
      });
      await page.goto(`${BASE}/?seed=42&renderTest`, { waitUntil: "load" });
      const dom = await page.evaluate(() => ({
        img: !!document.querySelector('img[data-aircraft-img="airliner"]'),
        fb: !!document.querySelector('[data-aircraft-fallback="airliner"]'),
        radio: !!document.querySelector('input[name="aircraft"][value="airliner"]'),
      }));
      expect(dom).toEqual({ img: true, fb: true, radio: true });
      await page.waitForFunction(
        () =>
          (document.querySelector('img[data-aircraft-img="airliner"]') as HTMLImageElement)
            ?.dataset.state === "failed",
        undefined,
    { timeout: 120_000 },
    );
      // the other eight cards settle — the set holds no hidden placeholders
      await page.waitForFunction(
        () =>
          [...document.querySelectorAll("img[data-theme-img], img[data-aircraft-img]")].every((img) => {
            const s = (img as HTMLImageElement).dataset.state;
            return s === "ready" || s === "failed";
          }),
        undefined,
    { timeout: 120_000 },
    );
      const card = await page.evaluate(() => {
        const img = document.querySelector(
          'img[data-aircraft-img="airliner"]',
        ) as HTMLImageElement;
        const fb = document.querySelector(
          '[data-aircraft-fallback="airliner"]',
        ) as HTMLElement;
        const input = document.querySelector(
          'input[name="aircraft"][value="airliner"]',
        ) as HTMLInputElement;
        return {
          state: img.dataset.state,
          src: img.getAttribute("src"),
          fbState: fb.dataset.state,
          fbText: fb.textContent?.trim() ?? "",
          fbVisible: fb.offsetParent !== null,
          name: input.closest("label.card")?.querySelector(".name")?.textContent ?? "",
          radioDisabled: input.disabled,
        };
      });
      expect(card.state).toBe("failed");
      expect(card.fbState).toBe("failed");
      expect(card.fbVisible).toBe(true);
      expect(card.fbText).toContain("preview unavailable");
      expect(card.name).toBe("Passenger Jet");
      expect(card.radioDisabled).toBe(false);
      // no picture attached — and never some other card's picture
      expect(card.src).toBeNull();
      const others = await page.evaluate(() => {
        const airliner = document.querySelector('img[data-aircraft-img="airliner"]');
        return [...document.querySelectorAll("img[data-theme-img], img[data-aircraft-img]")]
          .filter((i) => i !== airliner)
          .map((i) => (i as HTMLImageElement).currentSrc || (i as HTMLImageElement).src);
      });
      expect(others).not.toContain(card.src);
      // the radio still selects without a working preview
      await page.click('input[name="aircraft"][value="airliner"]');
      const checked = await page.evaluate(
        () =>
          (document.querySelector('input[name="aircraft"][value="airliner"]') as HTMLInputElement)
            .checked,
      );
      expect(checked).toBe(true);
      // a startup error is announced (not silent)
      const error = await page.evaluate(
        () => document.getElementById("chooser-error")?.textContent ?? "",
      );
      expect(error.length).toBeGreaterThan(0);
      // Retry completes the card once the injection clears — Fly retries failed previews
      await page.evaluate(() => {
        (window as unknown as { __verifyPreview?: unknown }).__verifyPreview = undefined;
      });
      await page.click("#fly");
      await page.waitForFunction(
        () =>
          (document.querySelector('img[data-aircraft-img="airliner"]') as HTMLImageElement)
            ?.dataset.state === "ready",
        undefined,
    { timeout: 120_000 },
    );
      const cards = await cardInfo(page, "aircraft");
      expect(cards.airliner.state).toBe("ready");
      expect(cards.airliner.src).toMatch(/^blob:/);
      expect(cards.airliner.w).toBe(256);
      expect(cards.airliner.h).toBe(144);
      expect(errs.pageErrors).toEqual([]);
    } finally {
      await page.close();
    }
  });
});
